a = str(input("a: "))
a = a.replace(',', '.')
a = float(a)
b = str(input("b: "))
b = b.replace(',', '.')
b = float(b)
s = round(a + b, 2)
avg = round(s / 2, 2)
print('sum=', s, '; avg=', avg, sep='')
