p = int(input("Введите цену:"))
d = int(input("Введите скидку:"))
v = int(input("Введите налог: "))
b = round(p * (1 - d/100), 2)
vr = round(b * (v/100), 2)
t = round(b + vr, 2)
print(f"База после скидки: {b}₽")
print(f"НДС:               {vr}₽")
print(f"Итого к оплате:    {t}₽")
